# Site settings
title: Jungmin Kim, Devloper
description: Jungmin Kim, Devloper
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jungmin Kim, Developer
user_description: Undefined
user_title: Embedded Software Developer <br/>Web Backend Developer
email: kjm99d@naver.com
#twitter_username: lorem_ipsum
github_username:  kjm99d
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
